//services
export const FETCH_SERVICES_PENDING = 'FETCH_SERVICES_PENDING';
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';
export const FETCH_SERVICES_ERROR = 'FETCH_SERVICES_ERROR ';
//register
export const OPEN_REGISTER_DIALOG = "OPEN_REGISTER_DIALOG";
export const CLOSE_REGISTER_DIALOG = "CLOSE_REGISTER_DIALOG";
//login
export const OPEN_LOGIN_DIALOG = "OPEN_LOGIN_DIALOG";
export const CLOSE_LOGIN_DIALOG = "CLOSE_LOGIN_DIALOG";
export const HANDLE_LOGOUT = "HANDLE_LOGOUT";
//products
export const FETCH_PRODUCTS_PENDING = 'FETCH_PRODUCTS_PENDING';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR';

export const HADLE_LOGIN_PENDING = "HADLE_LOGIN_PENDING";
export const HADLE_LOGIN_SUCCESS = "HADLE_LOGIN_SUCCESS";
export const HADLE_LOGIN_ERROR = "HADLE_LOGIN_ERROR";
//barber
export const FETCH_BARBERS_PENDING = 'FETCH_BARBERS_PENDING';
export const FETCH_BARBERS_SUCCESS = 'FETCH_BARBERS_SUCCESS';
export const FETCH_BARBERS_ERROR = 'FETCH_BARBERS_ERROR ';

//cart
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART"

export const HANDLE_ORDER_MAKE_PENDING = "HANDLE_ORDER_MAKE_PENDING";
export const HANDLE_ORDER_MAKE_SUCCESS = "HANDLE_ORDER_MAKE_SUCCESS";
export const HANDLE_ORDER_MAKE_ERROR = "HANDLE_ORDER_MAKE_ERROR";

