//services
export const FETCH_SERVICES_PENDING = 'FETCH_SERVICES_PENDING';
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';
export const FETCH_SERVICES_ERROR = 'FETCH_SERVICES_ERROR ';
//register
export const OPEN_REGISTER_DIALOG = "OPEN_REGISTER_DIALOG";
export const CLOSE_REGISTER_DIALOG = "CLOSE_REGISTER_DIALOG";
//login
export const OPEN_LOGIN_DIALOG = "OPEN_LOGIN_DIALOG";
export const CLOSE_LOGIN_DIALOG = "CLOSE_LOGIN_DIALOG";
//products
export const FETCH_PRODUCTS_PENDING = 'FETCH_PRODUCTS_PENDING';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR';

export const HADLE_LOGIN_PENDING = "HADLE_LOGIN_PENDING";
export const HADLE_LOGIN_SUCCESS = "HADLE_LOGIN_SUCCESS";
export const HADLE_LOGIN_ERROR = "HADLE_LOGIN_ERROR";

