//services
export const FETCH_SERVICES_PENDING = 'FETCH_SERVICES_PENDING';
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';
export const FETCH_SERVICES_ERROR = 'FETCH_SERVICES_ERROR ';
//login
export const OPEN_LOGIN_DIALOG = "OPEN_LOGIN_DIALOG";
export const CLOSE_LOGIN_DIALOG = "CLOSE_LOGIN_DIALOG";

export const HADLE_LOGIN_PENDING = "HADLE_LOGIN_PENDING";
export const HADLE_LOGIN_SUCCESS = "HADLE_LOGIN_SUCCESS";
export const HADLE_LOGIN_ERROR = "HADLE_LOGIN_ERROR";

